name: channel_talk_flutter_plus
description: A plugin that translates the Channel Talk SDK into a plugin for Flutter(Unofficial)
version: 2.4.0
homepage: https://github.com/aidl-inc/channel_talk_flutter_plus

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: ai.deepnatural.channel_talk
        pluginClass: ChannelTalkFlutterPlugin
      ios:
        pluginClass: ChannelTalkFlutterPlugin
